-- Create contact_submissions table for the website contact form
-- Run this in your Supabase dashboard SQL editor or via CLI

CREATE TABLE IF NOT EXISTS contact_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  company TEXT DEFAULT '',
  service TEXT DEFAULT '',
  message TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (the contact form doesn't require auth)
CREATE POLICY "Allow anonymous inserts" ON contact_submissions
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Allow only authenticated users to view submissions
CREATE POLICY "Allow authenticated select" ON contact_submissions
  FOR SELECT
  TO authenticated
  USING (true);
